-
  name: Remove  users to web_server
  hosts: all
  gather_facts: false
  tasks:
    - user:
        name: "{{ item }}"
        state: absent
        groups: osboxes,root
        remove: yes

      loop:
      - cartola
      - katia
      - eddie

      when: 'ansible_host=="10.0.0.122"'
